FROM node:18-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
