apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eam-secrets-provider
spec:
  provider: azure
  secretObjects:
    - secretName: eam-secrets
      type: Opaque
      data:
        - objectName: postgres-admin-password
          key: postgres-password
        - objectName: postgres-admin-password-urlencoded
          key: postgres-password-urlencoded
        - objectName: jwt-secret-key
          key: jwt-secret-key
        - objectName: groq-api-key
          key: groq-api-key
        - objectName: smtp-password
          key: smtp-password
        - objectName: ngrok-authtoken
          key: ngrok-authtoken
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
        - |
          objectName: postgres-admin-password-urlencoded
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
        - |
          objectName: groq-api-key
          objectType: secret
        - |
          objectName: smtp-password
          objectType: secret
        - |
          objectName: ngrok-authtoken
          objectType: secret
