"""Make ordre_travail_id nullable

Revision ID: 55c181562e1e
Revises: be6721db2847
Create Date: 2026-03-30 09:37:03.797912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55c181562e1e"
down_revision = "be6721db2847"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ordres_intervention",
        "ordre_travail_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ordres_intervention",
        "ordre_travail_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
