"""auto update

Revision ID: db0b16342160
Revises:
Create Date: 2026-01-27 03:03:55.474636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db0b16342160"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archives",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant_archive", sa.String(), nullable=False),
        sa.Column("nom", sa.String(), nullable=False),
        sa.Column("date_archivage", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=True),
        sa.Column("ordre_travail_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_archives_id"), "archives", ["id"], unique=False)
    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant_machine", sa.String(), nullable=False),
        sa.Column("nom", sa.String(), nullable=False),
        sa.Column("emplacement", sa.String(), nullable=False),
        sa.Column("statut", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "date_derniere_maintenance", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "date_prochaine_maintenance", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_machines_id"), "machines", ["id"], unique=False)
    op.create_table(
        "MaintenancesPlanifiees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=True),
        sa.Column("rapport_id", sa.Integer(), nullable=True),
        sa.Column("date_planifiee", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_MaintenancesPlanifiees_id"),
        "MaintenancesPlanifiees",
        ["id"],
        unique=False,
    )
    op.create_table(
        "ordres",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant", sa.String(), nullable=False),
        sa.Column("titre", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_creation", sa.DateTime(timezone=True), nullable=False),
        sa.Column("statut", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ordres_id"), "ordres", ["id"], unique=False)
    op.create_table(
        "OrdresIntervention",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_intervention", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rapport", sa.String(), nullable=True),
        sa.Column("ordre_travail_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_OrdresIntervention_id"), "OrdresIntervention", ["id"], unique=False
    )
    op.create_table(
        "OrdresTravail",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_echeance", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priorite", sa.String(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=True),
        sa.Column("ordre_id", sa.Integer(), nullable=True),
        sa.Column("statut", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_OrdresTravail_id"), "OrdresTravail", ["id"], unique=False
    )
    op.create_table(
        "planning_OrdresTravail",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("planning_id", sa.Integer(), nullable=False),
        sa.Column("ordre_travail_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_OrdresTravail_id"),
        "planning_OrdresTravail",
        ["id"],
        unique=False,
    )
    op.create_table(
        "PlanningUtilisateurs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("planning_id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_PlanningUtilisateurs_id"),
        "PlanningUtilisateurs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "plannings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant_planning", sa.String(), nullable=False),
        sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plannings_id"), "plannings", ["id"], unique=False)
    op.create_table(
        "rapports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant_rapport", sa.String(), nullable=False),
        sa.Column("titre", sa.String(), nullable=False),
        sa.Column("date_generation", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contenu", sa.String(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rapports_id"), "rapports", ["id"], unique=False)
    op.create_table(
        "utilisateurs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifiant", sa.String(), nullable=False),
        sa.Column("nom", sa.String(), nullable=False),
        sa.Column("mot_de_passe", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_utilisateurs_id"), "utilisateurs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_utilisateurs_id"), table_name="utilisateurs")
    op.drop_table("utilisateurs")
    op.drop_index(op.f("ix_rapports_id"), table_name="rapports")
    op.drop_table("rapports")
    op.drop_index(op.f("ix_plannings_id"), table_name="plannings")
    op.drop_table("plannings")
    op.drop_index(
        op.f("ix_PlanningUtilisateurs_id"), table_name="PlanningUtilisateurs"
    )
    op.drop_table("PlanningUtilisateurs")
    op.drop_index(
        op.f("ix_planning_OrdresTravail_id"), table_name="planning_OrdresTravail"
    )
    op.drop_table("planning_OrdresTravail")
    op.drop_index(op.f("ix_OrdresTravail_id"), table_name="OrdresTravail")
    op.drop_table("OrdresTravail")
    op.drop_index(op.f("ix_OrdresIntervention_id"), table_name="OrdresIntervention")
    op.drop_table("OrdresIntervention")
    op.drop_index(op.f("ix_ordres_id"), table_name="ordres")
    op.drop_table("ordres")
    op.drop_index(
        op.f("ix_MaintenancesPlanifiees_id"), table_name="MaintenancesPlanifiees"
    )
    op.drop_table("MaintenancesPlanifiees")
    op.drop_index(op.f("ix_machines_id"), table_name="machines")
    op.drop_table("machines")
    op.drop_index(op.f("ix_archives_id"), table_name="archives")
    op.drop_table("archives")
    # ### end Alembic commands ###
