"""add_status_shift_type_to_utilisateurs

Revision ID: f44d6d0416f4
Revises: b7c8d9e0f1a3
Create Date: 2026-03-28 13:25:57.025945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f44d6d0416f4"
down_revision: Union[str, Sequence[str], None] = "b7c8d9e0f1a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("machines", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "machines", "emplacement", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("machines", "statut", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("machines", "identifiant_machine")
    op.alter_column(
        "ml_prediction_logs",
        "is_anomaly",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "ml_prediction_logs",
        "ml_model_used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_ml_prediction_logs_id"), "ml_prediction_logs", ["id"], unique=False
    )
    op.alter_column(
        "OrdresIntervention",
        "statut",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "OrdresIntervention",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    bind = op.get_bind()
    retrained_exists = bind.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name='OrdresIntervention' AND column_name='retrained'"
        )
    ).first()
    if retrained_exists:
        op.alter_column(
            "OrdresIntervention",
            "retrained",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=True,
        )
    else:
        op.add_column(
            "OrdresIntervention",
            sa.Column("retrained", sa.Boolean(), nullable=True),
        )
    problem_start_time_exists = bind.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name='OrdresIntervention' AND column_name='problem_start_time'"
        )
    ).first()
    if problem_start_time_exists:
        op.alter_column(
            "OrdresIntervention",
            "problem_start_time",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
    else:
        op.add_column(
            "OrdresIntervention",
            sa.Column("problem_start_time", sa.DateTime(timezone=True), nullable=True),
        )
    op.drop_index(
        op.f("ix_OrdresIntervention_statut"), table_name="OrdresIntervention"
    )
    op.drop_index(
        op.f("ix_OrdresIntervention_technicien_id"), table_name="OrdresIntervention"
    )
    op.alter_column(
        "OrdresTravail",
        "priorite",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "OrdresTravail",
        "statut",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    def _column_exists(table_name, column_name):
        return bind.execute(
            sa.text(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_name=:t AND column_name=:c"
            ),
            {"t": table_name, "c": column_name},
        ).first()

    if _column_exists("OrdresTravail", "date_validation"):
        op.alter_column(
            "OrdresTravail",
            "date_validation",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
    else:
        op.add_column(
            "OrdresTravail",
            sa.Column("date_validation", sa.DateTime(timezone=True), nullable=True),
        )
    # These columns are pure ad-hoc dev-DB drift not tracked by any earlier
    # migration and not present in the current model -- dropping them is a
    # no-op if they were never actually created.
    for _col in (
        "created_by_id",
        "validated_at",
        "completed_at",
        "estimated_duration_minutes",
        "validated_by_id",
        "assigned_at",
    ):
        if _column_exists("OrdresTravail", _col):
            op.drop_column("OrdresTravail", _col)
    op.drop_index(
        op.f("ix_PlanningMachines_machine_id"), table_name="PlanningMachines"
    )
    op.drop_index(
        op.f("ix_PlanningMachines_planning_id"), table_name="PlanningMachines"
    )
    op.drop_constraint(
        op.f("uq_PlanningMachines_planning_machine"),
        "PlanningMachines",
        type_="unique",
    )
    op.create_index(
        op.f("ix_PlanningMachines_id"), "PlanningMachines", ["id"], unique=False
    )
    # alter_column with an Enum type_ does NOT auto-create the Postgres enum
    # type the way adding a new enum column would -- on a genuinely fresh DB
    # these types were never created. checkfirst=True makes this a no-op
    # wherever the type already exists (e.g. from earlier dev-DB drift).
    planningtype_enum = sa.Enum(
        "MAINTENANCE",
        "SHIFT",
        "HEBDOMADAIRE",
        "MENSUEL",
        "JOURNALIER",
        name="planningtype",
    )
    planningtype_enum.create(bind, checkfirst=True)
    op.alter_column(
        "plannings",
        "type",
        existing_type=sa.VARCHAR(),
        type_=planningtype_enum,
        existing_nullable=False,
        postgresql_using="type::planningtype",
    )
    shifttype_enum = sa.Enum("MORNING", "NIGHT", name="shifttype")
    shifttype_enum.create(bind, checkfirst=True)
    if bind.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name='plannings' AND column_name='shift_type'"
        )
    ).first():
        op.alter_column(
            "plannings",
            "shift_type",
            existing_type=sa.VARCHAR(),
            type_=shifttype_enum,
            existing_nullable=True,
            postgresql_using="shift_type::shifttype",
        )
    else:
        op.add_column("plannings", sa.Column("shift_type", shifttype_enum, nullable=True))

    userrole_enum = sa.Enum("TECHNICIEN", "CHEFTECH", "CHETOP", "ADMIN", name="userrole")
    userrole_enum.create(bind, checkfirst=True)
    op.alter_column(
        "utilisateurs",
        "role",
        existing_type=sa.VARCHAR(),
        type_=userrole_enum,
        existing_nullable=False,
        postgresql_using="role::userrole",
    )
    op.alter_column(
        "utilisateurs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("uq_utilisateurs_email"), "utilisateurs", type_="unique")
    op.drop_index(op.f("ix_utilisateurs_email"), table_name="utilisateurs")
    op.create_index(
        op.f("ix_utilisateurs_email"), "utilisateurs", ["email"], unique=True
    )
    op.drop_column("utilisateurs", "identifiant")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "utilisateurs",
        sa.Column("identifiant", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_utilisateurs_email"), table_name="utilisateurs")
    op.create_index(
        op.f("ix_utilisateurs_email"), "utilisateurs", ["email"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_utilisateurs_email"),
        "utilisateurs",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "utilisateurs",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "utilisateurs",
        "role",
        existing_type=sa.Enum(
            "TECHNICIEN", "CHEFTECH", "CHETOP", "ADMIN", name="userrole"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("utilisateurs", "updated_at")
    op.drop_column("utilisateurs", "shift_type")
    op.drop_column("utilisateurs", "status")
    op.alter_column(
        "plannings",
        "shift_type",
        existing_type=sa.Enum("MORNING", "NIGHT", name="shifttype"),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "plannings",
        "type",
        existing_type=sa.Enum(
            "MAINTENANCE",
            "SHIFT",
            "HEBDOMADAIRE",
            "MENSUEL",
            "JOURNALIER",
            name="planningtype",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_PlanningMachines_id"), table_name="PlanningMachines")
    op.create_unique_constraint(
        op.f("uq_PlanningMachines_planning_machine"),
        "PlanningMachines",
        ["planning_id", "machine_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_PlanningMachines_planning_id"),
        "PlanningMachines",
        ["planning_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_PlanningMachines_machine_id"),
        "PlanningMachines",
        ["machine_id"],
        unique=False,
    )
    op.add_column(
        "OrdresTravail",
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "OrdresTravail",
        sa.Column("validated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "OrdresTravail",
        sa.Column(
            "estimated_duration_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "OrdresTravail",
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "OrdresTravail",
        sa.Column(
            "validated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "OrdresTravail",
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "OrdresTravail",
        "date_validation",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "OrdresTravail",
        "statut",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'EN_ATTENTE'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "OrdresTravail",
        "priorite",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'MOYENNE'::character varying"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_OrdresIntervention_technicien_id"),
        "OrdresIntervention",
        ["technicien_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_OrdresIntervention_statut"),
        "OrdresIntervention",
        ["statut"],
        unique=False,
    )
    op.alter_column(
        "OrdresIntervention",
        "problem_start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "OrdresIntervention",
        "retrained",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "OrdresIntervention",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "OrdresIntervention",
        "statut",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'EN_ATTENTE'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_ml_prediction_logs_id"), table_name="ml_prediction_logs")
    op.alter_column(
        "ml_prediction_logs",
        "ml_model_used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.alter_column(
        "ml_prediction_logs",
        "is_anomaly",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    op.add_column(
        "machines",
        sa.Column(
            "identifiant_machine", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column("machines", "statut", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "machines", "emplacement", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("machines", "type", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
